version: '3.2'
    
services:
  nginx:
    image: nginxproxy/nginx-proxy 
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./conf:/etc/nginx/conf.d
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - default
      - nginx

  acme:
    image: nginxproxy/acme-companion
    container_name: acme
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./conf:/etc/nginx/conf.d
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - DEFAULT_EMAIL=your@email.com
    depends_on:
      - nginx

volumes:
    dhparam:
    vhost:
    html:
    acme:

networks:
  nginx:
    attachable: true